version: "3.7"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes: 
      - ./db/migrations:/migrations
    container_name: sanma-db
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
